layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: VorTX3735
  # hackerrank: your_username
  instagram: vortx3735
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: vortx3735
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: channel/UCxOHt6h_aFeYcS7nnuXV1mw

topics:
  - name: Programming
    web_url: https://docs.wpilib.org/en/stable/index.html
    image_url: https://docs.wpilib.org/en/stable/_static/wpilibDocsLogo.png

  - name: First Robotics Competition
    web_url: https://www.firstinspires.org/robotics/frc
    image_url: https://cdn.imgbin.com/23/24/8/imgbin-first-robotics-competition-first-tech-challenge-first-power-up-first-stronghold-for-inspiration-and-recognition-of-science-and-technology-robotics-fh00PjpaDihv3ZcNCtf1ZzbE6.jpg

  - name: Building Robots
    image_url: https://cdn.discordapp.com/attachments/927623390406250537/970384532094189598/unknown.png
